### ISSUE TITLE
runtime_tag label populated via setting NEURON_PROCESS_TAG is truncated before 255 characters

### ISSUE THREAD

**Issue by sidd-pandey** [aws-neuron/aws-neuron-sdk#1149]
According to the docs https://awsdocs-neuron.readthedocs-hosted.com/en/latest/tools/neuron-sys-tools/neuron-monitor-user-guide.html#neuron-applications-tagging, `NEURON_PROCESS_TAG` supports 255 character. 

> In order to make application monitoring easier, Neuron applications can be tagged with a 255 character string which identifies that app. Tagging is done using the NEURON_PROCESS_TAG environment variable.

But seems that it gets prematurely truncated at **31** characters. The metric is exported via prometheus endpoint exposed in the pod created by the neuron-monitor daemonset (https://awsdocs-neuron.readthedocs-hosted.com/en/latest/tools/neuron-sys-tools/neuron-monitor-user-guide.html#running-neuron-monitor-in-kubernetes-environment). 

Additional information:
1. Neuron monitor daemonset image: `public.ecr.aws/neuron/neuron-monitor:1.4.0`
2. From monitor pod:
```
neuron-monitor --version
neuron-monitor 2.22.61.0%kaena-tools/2.22@8b70825 built on 2025-03-19T02:14:55Z
```
3. The `NEURON_PROCESS_TAG` env variable is set via kubernetes downward api to match the pod name. 
```yaml
- name: NEURON_PROCESS_TAG
  valueFrom:
    fieldRef:
      fieldPath: metadata.name
```
4. For testing, specifying the `NEURON_PROCESS_TAG` variable as inline shell variable is also tried.
```yaml
      containers:
      - command:
        - /bin/sh
        - -c
        - NEURON_PROCESS_TAG=the-quick-brown-fox-jumps-over-the-lazy-dog torchserve
          --start --ts-config /var/conf/config.properties --foreground
```
In both cases, the `runtime_tag` is truncated. Here is an example of metrics from prom server running at port `8000` by default in the neuron monitor pod.

```
execution_status_total{availability_zone="ap-southeast-1c",instance_id="i-xxx",instance_name="",instance_type="inf1.2xlarge",region="ap-southeast-1",runtime_tag="the-quick-brown-fox-jumps-over-",status_type="completed",subnet_id="subnet-xxx"} 0.0
...
...
neuron_runtime_memory_used_bytes{availability_zone="ap-southeast-1c",instance_id="i-xxx",instance_name="",instance_type="inf1.2xlarge",memory_location="host",region="ap-southeast-1",runtime_tag="the-quick-brown-fox-jumps-over-",subnet_id="subnet-xxx"} 0.0

```
Notice the truncated the label `runtime_tag="the-quick-brown-fox-jumps-over-"`.
