### ISSUE TITLE
Getting no neuron devices available on an inf1 instance using aws provided containers

### ISSUE THREAD

**Issue by sanjay23singh** [aws-neuron/aws-neuron-sdk#633]
Hi, 
I used the following neuron container image provided by aws as a base image and ran that on an **inf1** instance.
`763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-inference-neuron:1.12.1-neuron-py38-sdk2.5.0-ubuntu20.04`

But i am getting 
`TDRV: tdrv_get_dev_info     No neuron device available`
`NRT: nrt_init     This instance has no neuron devices. please run on an instance that supports Neuron, for example inf1`

**For `neuron-ls` we are getting this:**

`FATA[0000] Failed to discover neuron devices             error="Unable to read device information from the driver. Make sure aws-neuronx-dkms is installed and the neuron driver is accessible."`

**and for `neuron-monitor` we are getting this:**

`{"neuron_runtime_data":[],"system_data":{"memory_info":{"period":0.000690876,"memory_total_bytes":16299401216,"memory_used_bytes":6843494400,"swap_total_bytes":0,"swap_used_bytes":0,"error":""},"neuron_hw_counters":{"period":0.000694819,"neuron_devices":null,"error":""},"vcpu_usage":{"period":0.000692292,"average_usage":{"user":0,"nice":0,"system":0,"idle":100,"io_wait":0,"irq":0,"soft_irq":0},"usage_data":{"0":{"user":0,"nice":0,"system":0,"idle":0,"io_wait":0,"irq":0,"soft_irq":0},"1":{"user":0,"nice":0,"system":0,"idle":0,"io_wait":0,"irq":0,"soft_irq":0},"2":{"user":0,"nice":0,"system":0,"idle":0,"io_wait":0,"irq":0,"soft_irq":0},"3":{"user":0,"nice":0,"system":0,"idle":0,"io_wait":0,"irq":0,"soft_irq":0},"4":{"user":0,"nice":0,"system":0,"idle":0,"io_wait":0,"irq":0,"soft_irq":0},"5":{"user":0,"nice":0,"system":0,"idle":0,"io_wait":0,"irq":0,"soft_irq":0},"6":{"user":0,"nice":0,"system":0,"idle":0,"io_wait":0,"irq":0,"soft_irq":0},"7":{"user":0,"nice":0,"system":0,"idle":0,"io_wait":0,"irq":0,"soft_irq":0}},"context_switch_count":30,"error":""}},"instance_info":{"instance_name":"","instance_id":"i-02df359bfd141d5f9","instance_type":"inf1.2xlarge","instance_availability_zone":"ap-south-1a","instance_availability_zone_id":"aps1-az1","instance_region":"ap-south-1","ami_id":"ami-02a9483e45d986892","subnet_id":"subnet-0a68f664828e27c55","error":""},"neuron_hardware_info":{"neuron_device_count":0,"neuroncore_per_device_count":0,"error":"no Neuron Device found - make sure the aws-neuronx-dmks package is installed"}}`

Is there something I am missing while dealing with neuron?

**Comment by micwade-aws** [comment]
Taking a look @sanjay23singh

**Comment by micwade-aws** [comment]
@sanjay23singh - The most common cause of this is either a host that's not running the Neuron Driver or a container that was started without mounting the Neuron Device(s).

If the errors came directly from the host, please try [re-installing or updating](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/setup/index.html#setup-guide-index) to the latest Neuron Driver on the host (not inside the container).

If the errors came from within the container, double check that the container was started with Neuron Devices mounted (--device=/dev/neuron0).

Would it be possible for you to share your container launch command and possibly the output of these two commands from the host? 
```
lsmod | grep neuron
modinfo neuron
```

**Comment by sanjay23singh** [comment]
![inferentia_issus](https://user-images.githubusercontent.com/47422067/221507261-df95b104-91a7-4a4a-81a4-a9b8e2fa1c7a.png)

@micwade-aws this is the output of the above commands.

**Comment by sanjay23singh** [comment]
hi @micwade-aws 

we are running our container on Kubernetes via the **neuron device plugin daemonset** with the following configurations,

OS Image:   Amazon Linux 2
Architecture: amd64
Kubernetes version :  v1.20.15-eks
Container Runtime Version:  docker://20.10.17
instance-type: inf1.2xlarge

Let me know if you require more info.

**Comment by james-aws** [comment]
hi @sanjay23singh, your problem is likely caused by a misconfiguration or not properly requesting neuron resources. One possibility is that you are missing the `aws.amazon.com/neuron` resource in your deployment yaml.
I have launched a EKS cluster and deployed the container image you are using. With this setup neuron devices are correctly setup and accessible from within the container. The following is my yaml deployment file.
```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: eks-neuron-test
  labels:
    app: eks-neuron-test
    role: master
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-neuron-test
      role: master
  template:
    metadata:
      labels:
        app: eks-neuron-test
        role: master
    spec:
      containers:
        - name: eks-neuron-test
          image: 763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-inference-neuron:1.12.1-neuron-py38-sdk2.5.0-ubuntu20.04
          ports:
            - containerPort: 8500
            - containerPort: 9000
          resources:
            limits:
              cpu: 4
              memory: 4Gi
              aws.amazon.com/neuron: 1
            requests:
              cpu: "1"
              memory: 1Gi
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
```
You will notice the line `aws.amazon.com/neuron: 1` which will allocate 1 Neuron device to your container.

I am then able to connect to the container and run neuron-ls to see the available Neuron resources.
```
root@eks-neuron-test:/# neuron-ls
instance-type: inf1.2xlarge
+--------+--------+--------+---------+
| NEURON | NEURON | NEURON |   PCI   |
| DEVICE | CORES  | MEMORY |   BDF   |
+--------+--------+--------+---------+
| 0      | 4      | 8 GB   | 00:1f.0 |
```

The following guide covers creating an EKS cluster with inf1 nodes and deploying an application image.
https://docs.aws.amazon.com/eks/latest/userguide/inferentia-support.html
